#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Sat Oct 28 17:46:01 2023
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MyFrame import MyFrame


class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app_for_text_copy_format = MyApp(0)
    app_for_text_copy_format.MainLoop()
