# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Sat Oct 28 17:46:01 2023
#

import wx

from func import convertFunction


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((973, 537))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_title = wx.StaticText(self.panel_1, wx.ID_ANY, u"文本格式处理工具1.0 by eaton liyu")
        label_title.SetFont(wx.Font(19, wx.FONTFAMILY_MODERN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 1, ""))
        sizer_2.Add(label_title, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "input_box"), wx.VERTICAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        label_input = wx.StaticText(self.panel_1, wx.ID_ANY, "input:")
        sizer_3.Add(label_input, 0, 0, 0)

        self.text_ctrl_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "将文本复制粘贴到这里", style=wx.TE_MULTILINE)
        self.text_ctrl_input.SetMinSize((951, 23))
        sizer_3.Add(self.text_ctrl_input, 1, wx.ALL, 0)

        sizer_4 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_2.Add(sizer_4, 0, wx.ALL | wx.EXPAND, 0)

        self.button_sure = wx.Button(self.panel_1, wx.ID_ANY, u"输出")
        sizer_4.Add(self.button_sure, 0, 0, 0)

        self.button_clean = wx.Button(self.panel_1, wx.ID_ANY, u"清空")
        sizer_4.Add(self.button_clean, 0, 0, 0)

        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "output"), wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)

        self.text_ctrl_output = wx.TextCtrl(self.panel_1, wx.ID_ANY, "123", style=wx.TE_READONLY)
        self.text_ctrl_output.SetMinSize((12, 23))
        sizer_5.Add(self.text_ctrl_output, 1, wx.ALL | wx.EXPAND, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.button_sure.Bind(wx.EVT_BUTTON, self.buttonOut)
        self.button_clean.Bind(wx.EVT_BUTTON, self.buttonClean)
        # end wxGlade

    def buttonOut(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'button_out' running!")
        self.text_ctrl_output.SetValue("")
        text = self.text_ctrl_input.GetValue()
        res = convertFunction(text)
        self.text_ctrl_output.SetValue(res)
        # event.Skip()

    def buttonClean(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'button_clean' running")
        self.text_ctrl_output.SetValue("")
        self.text_ctrl_input.SetValue("")
        # event.Skip()

# end of class MyFrame
